### ISSUE TITLE
Создать класс Popup

### ISSUE THREAD

**Issue by stelzf117** [stelzf117/mesto-project#9]

**Comment by stelzf117** [comment]
После необходимо @stelzf117 связать класс с классом Card

**Comment by aleksr777** [comment]
Предлагаю в git далее сделать ответвления от ветки 'futures/class-popup', чтобы красиво было:
'futures/popup-with-form'
'futures/popup-with-image'

**Comment by aleksr777** [comment]
Постараюсь сегодня сделать классы Popap и PopupWithForm, чтобы можно было проверить их работоспособность, и отправлю пулреквест с обеими классами.
